### ISSUE TITLE
ToC highlighting UI shifts

### ISSUE THREAD

**Issue by HiDeoo** [withastro/starlight#1120]
### What version of `starlight` are you using?

0.13.0

### What version of `astro` are you using?

3.6.0

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

While browsing the new Astro Docs in the Starlight migration branch, I noticed that the table of contents highlighting styles can lead to some visually distracting UI shifts that I never noticed before but this is happening a lot in the Astro v3 migration guide for example.

Here is a video of the issue where I am just scrolling the page:

https://github.com/withastro/starlight/assets/494699/39039404-bd68-49b0-84a8-79ab1b9213aa

_Note: I pasted the content of this page in our repo and this repro too so this is not related to some changes that may have been made in the migration branch._

### Link to Minimal Reproducible Example

https://docs-git-fork-theotterlord-starlight-migration-astrodotbuild.vercel.app/en/guides/upgrade-to/v3/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Ah yes, I’ve noticed this before. You can also see it on “Automatic heading anchor links” in the ToC of https://starlight.astro.build/guides/authoring-content/ if you make the window narrow enough. It makes total sense because the font-weight changes, meaning the text takes up more space.

Fixing it could mean avoiding the font-weight change, although the inverted text does look a little less nice in a lighter weight:

| Current | Without bolder text |
|---|---|
| <img width="305" alt="" src="https://github.com/withastro/starlight/assets/357379/65494162-80b9-4108-b875-98c65bcc63b8"> | <img width="313" alt="" src="https://github.com/withastro/starlight/assets/357379/3da7050d-5e8c-4cb8-a024-e987a5068abc">

It would also be inconsistent with the left sidebar which follows the same pattern (and the same problem, although less noticeable because the layout shift can only happen across a page load).

Might be one I double check with @doodlemarks first before jumping to a solution.

**Comment by delucis** [comment]
Updating here with some feedback from @doodlemarks:

> My guidance would be just update the active state to have the accent color for the text and drop all the other styles.

Example screenshot of this in action:

<img width="272" alt="Starlight table of contents section showing one link in a soft blue accent with the other links in a subdued gray" src="https://github.com/withastro/starlight/assets/357379/012d8192-746d-4ea5-b677-d4f1167a9566">

Proposed CSS change:

```diff
a[aria-current="true"] {
- font-weight: 600;
- color: var(--sl-color-text-invert);
- background-color: var(--sl-color-text-accent);
+ color: var(--sl-color-text-accent);
}
```

Currently those styles are also applied on `:hover` and `:focus`, but with this update, I think we can remove that and let the default hover/focus styles kick in.
