### ISSUE TITLE
Missing "./constants" specifier in "@astrojs/starlight" package

### ISSUE THREAD

**Issue by kdheepak** [withastro/starlight#1161]
### What version of `starlight` are you using?

0.13.1

### What version of `astro` are you using?

3.2.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

I guess this is more of a question than a bug report.

I was trying to override the `Hero` component with a component that had the following frontmatter:

```
---
import { Image } from "astro:assets";
import { PAGE_TITLE_ID } from "@astrojs/starlight/constants";
import type { Props } from "@astrojs/starlight/props";
import CallToAction from "@astrojs/starlight/components/CallToAction.astro";
...
```

but wasn't able to import PAGE_TITLE_ID. Is that expected?

<img width="1290" alt="image" src="https://github.com/withastro/starlight/assets/1813121/283b50a2-a28c-46c6-b229-c53f6c95a913">

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report.

> but wasn't able to import PAGE_TITLE_ID. Is that expected?

Indeed, at the moment this is not possible. This is tracked in this [issue](https://github.com/withastro/starlight/issues/860) and more spefically this [comment](https://github.com/withastro/starlight/issues/860#issuecomment-1757457206) which contains a section regarding constants:

> Maybe we take a similar approach and expose constants on the route data objects as well to avoid documenting the extra export? I agree that it’s useful to have this exposed — I already had to use `_top` without the constant in [a docs example](https://starlight.astro.build/guides/overriding-components/#use-page-data).

The only workaround at the moment to use the [hardcoded string `_top`](https://github.com/withastro/starlight/blob/f82cb340532747aaadff451271df2d6a018d8231/packages/starlight/constants.ts) for now.

Note that depending on your need, it's also possible to [re-use](https://starlight.astro.build/guides/overriding-components/#reuse-a-built-in-component) the `<Hero/>` component built-in with Starlight in your component override so that you don't have to re-implement it from scratch and would not have this issue but it depends on your use case and what you want to achieve.

**Comment by kdheepak** [comment]
> Note that depending on your need, it's also possible to [re-use](https://starlight.astro.build/guides/overriding-components/#reuse-a-built-in-component) the <Hero/> component built-in with Starlight in your component override so that you don't have to re-implement it from scratch and would not have this issue but it depends on your use case and what you want to achieve.

Good idea! I wanted to change the layout of the `Hero` component and I assume that the only way was to reimplement it. I have hardcoded `_top` for now.
