### ISSUE TITLE
Built-in components are not tree shakable

### ISSUE THREAD

**Issue by yasnbouz** [withastro/starlight#1272]
### What version of `starlight` are you using?

0.15.0

### What version of `astro` are you using?

4.0.1

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

Even though my homepage only uses the `Card` component, the bundle still includes `CardGrid` and `Tabs`.
<img width="1064" alt="shapes at 23-12-12 13 08 29" src="https://github.com/withastro/starlight/assets/45861586/aba1f22c-5996-415b-bfc2-9a4ad846ea39">

The cause of this problem is the use of barrel files in [components.ts](https://github.com/withastro/starlight/blob/5df5798405ed0a29f0a2b2ca9252cda6e28e72a3/packages/starlight/components.ts), which re-export modules from one file. According to the [Vite.js documentation](https://vitejs.dev/guide/performance#avoid-barrel-files), we should avoid barrel files. Therefore, the solution is to enable individual imports of built-in components:

```
import { Card } from '@astrojs/starlight/components;
```
to
```
import Card from "@astrojs/starlight/components/Card.astro";
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mufzhv?file=src%2Fcontent%2Fdocs%2Findex.mdx

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
This is a known issue in Astro’s tree shaking. There have been some attempts to improve this — available with the [`experimental.optimizeHoistedScript`](https://docs.astro.build/en/reference/configuration-reference/#experimentaloptimizehoistedscript) option — but so far they are buggy for Starlight’s case (breaking JS inclusion even when used in some cases).

We did also consider non-barrel imports, but barrel entrypoints do have some nice advantages when thinking of imports that need to be used by content authors:

- Single import location to think of: `@astrojs/starlight/components`
- Import everything you need with one line — especially helpful for combos like `Tabs` and `TabItem` or `Card` and `CardGrid`

I agree that loading extra JS is not ideal though. Ideally, the fix comes from Astro (I can check with the team next week whether further work on this is planned), but otherwise I guess we could probably also export each component independently as well, so people can choose that path if they prefer.

**Comment by Fryuni** [comment]
> but otherwise I guess we could probably also export each component independently as well, so people can choose that path if they prefer.

The components are already available independently just by how ESM resolution works isn't it?

I believe this works and includes only the `Card` scripts in the page
```ts
import Card from '@astrojs/starlight/components/Card.astro';
```

Or is the idea to provide an import for each component that also resolves to the overriden component if any?

**Comment by delucis** [comment]
> The components are already available independently just by how ESM resolution works isn't it?

I don’t think so because these author-facing components are actually in the `user-components/` directory not `components/`. (And overriding doesn’t apply for these components — users can just import from somewhere else if they want to use a different implementation.)

But thanks again for the bump — I’ll check in with the team to see what the status of work on barrel file tree-shaking is.

**Comment by delucis** [comment]
Annnnd back with the update! @bluwy is planning to work on tree-shaking improvements in the coming week or two, that will hopefully address this.

Given this, I’ll close this as something we won’t fix in Starlight itself, but upstream in Astro. If for some reason Bjorn’s work doesn’t work out we can revisit that.
