### ISSUE TITLE
Can't deploy on Cloudflare

### ISSUE THREAD

**Issue by kasperaamodt** [withastro/starlight#1333]
### What version of `starlight` are you using?

0.15.2

### What version of `astro` are you using?

4.0.9

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Arc

### Describe the Bug

I can't deploy my project on Cloudflare pages. I'm getting the following error message for a lot of different node builtins.

```
The package "child_process" wasn't found on the file system but is built into node. Are you trying
to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

The only thing you need to do to recreate this error is to create a Starlight project, add the Cloudflare integration, and run a build.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kqbehi

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @kasperaamodt!

Starlight doesn't currently support SSR deployment (see [the docs](https://starlight.astro.build/manual-setup/#use-starlight-with-ssr), #1167 and #1255).

I've heard some people get things working with `output: 'hybrid'` instead of `'server'`, but we haven't been able to officially design or test that across all platforms yet.

If you don't need SSR and just a static docs site, deploying to Cloudflare Pages without the adapter and server output should work just fine! (The adapter is only need for dynamic server-rendered sites.)

Will close this issue as SSR support is technically a feature request and we're currently tracking it in #1167, but I'm happy to continue discussion here if you have any further questions!
