### ISSUE TITLE
 CSS not displaying on pages other than homepage

### ISSUE THREAD

**Issue by hexWars** [withastro/starlight#1373]
### What version of `starlight` are you using?

0.15.3

### What version of `astro` are you using?

4.0.1

### What package manager are you using?

yarn

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

I encountered an issue with the latest version of Starlight. After building, the CSS is not displaying, and the console shows the following error message: "Refused to apply style from 'http://localhost:63344/_astro/index.b6TRhTtz.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

I believe this is not my problem, and I kindly request the development team to investigate this issue when they have the time.

### Link to Minimal Reproducible Example

I'm sorry, I cannot provide a specific address.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report.

> After building, the CSS is not displaying

May I ask how you are serving the production build?

I may be going on a totally wrong track but it looks like the port `63344` is common for JetBrains IDEs with the built-in web server. If that's the case, it looks like there are several issues open for this feature regarding MIME types ([issue 1](https://youtrack.jetbrains.com/issue/WEB-47264/Built-in-web-server-missing-mime-types) - [issue 2](https://youtrack.jetbrains.com/issue/WEB-32451)).

If you are indeed using the JetBrains built-in web server, could you please try to serve the production build using the [`astro preview` command](https://docs.astro.build/en/reference/cli-reference/#astro-preview) (it should be `npm run preview` if you are using npm) after building your website for production and see if the issue persists when viewing the site at `http://localhost:4321`?

**Comment by hexWars** [comment]
Thank you for your response. I have no issues when using yarn preview, but the problem still persists when using the Live Server plugin in VS Code.

**Comment by delucis** [comment]
My guess here is that this the fault of `vscode-live-server`. After building, Starlight outputs a static folder containing pages and assets with typical extensions (e.g. `.css` in this case). A server should usually be smart enough to rely on those extensions to also set the MIME type.

Taking a quick look at Live Server’s 2,000+ GitHub issues (😬), I can see several which mention similar issues: https://github.com/ritwickdey/vscode-live-server/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+MIME

I suspect that’s the cause here and would advise sticking to the built-in `dev`, `build`, and `preview` commands.

**Comment by hexWars** [comment]
After using nginx, everything is back to normal. Thank you for your assistance.
