### ISSUE TITLE
Search not working in Cloudflare workers

### ISSUE THREAD

**Issue by riderx** [withastro/starlight#1532]
### What version of `starlight` are you using?

0.19.0

### What version of `astro` are you using?

4.4.0

### What package manager are you using?

bun 

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Search box does not render correctly.

https://github.com/withastro/starlight/assets/4084527/99cfd21d-f0e3-448b-a0c4-b6fe1b344ea6

if I run in local like that:
`bun run build && bun run preview`
No issue
if I do this:
`npx wrangler pages dev ./dist` the search is broken
You can also find the issue here: https://capgo.app/docs/

### Link to Minimal Reproducible Example

https://github.com/Cap-go/website

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Do you have Cloudflare’s [“Rocket Loader”](https://developers.cloudflare.com/speed/optimization/content/rocket-loader/) feature enabled? We’ve seen issues in the past with that because for some reason it prevents events firing on page load (which is when the search code executes).

**Comment by rishi-raj-jain** [comment]
My observations:

1. Something is defeinitely weird with CF Rocket Loader because as I block it to test the website without, it just doesn't load ANY JS
![image](https://github.com/withastro/starlight/assets/46300090/fbf5be80-1098-4e81-9b00-cf5371dcd954)

2. the cloudflare rocket loader mode is adding type="module" to all the script tags and they're being only by CF script, and don't load with CF scripts at all. and this all "optimization" is happening after you've deployed meaning we don't have control over it other than disabling it 😅 unless you'd wanna SSR but that just defeats the whole purpose of it.

**Comment by riderx** [comment]
yes it was rocket loader

**Comment by ofrades** [comment]
I think it's because of **bun** and not **cloudflare**. I have an app in cloudflare and usign `npm` was fine, when I tried to change to bun it broke the search. Even locally when doing `bun run build && npm run preview`.
