### ISSUE TITLE
Starlight not usable with typescript `declarations: true`

### ISSUE THREAD

**Issue by alexanderniebuhr** [withastro/starlight#1612]
### What version of `starlight` are you using?

0.21.1

### What version of `astro` are you using?

4.3.5

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Starlight is not usable if `"declaration": true,` is set in `tsconfig.json`.
This option however is mandatory for projects with `"composite": true`. _(Enable constraints that allow a TypeScript project to be used with project references.)_

The following issue occurs in `src/content/config.ts`

```
The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.(7056)
```

Potentially related to this is:

https://github.com/colinhacks/zod/issues/1040

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gx6te3?file=src%2Fcontent%2Fconfig.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Posting a small update of my findings so far.

This seems to be related to the recursion in [`BaseSchemaWithoutEffects`](https://github.com/withastro/starlight/blob/main/packages/starlight/schema.ts#L111C6-L115) (which is ultimately used to provide schema extensions), and more specifically these 2 parts of the union which reference the type itself:

```ts
  …
  | z.ZodUnion<[BaseSchemaWithoutEffects, ...BaseSchemaWithoutEffects[]]>
  …
  | z.ZodIntersection<BaseSchemaWithoutEffects, BaseSchemaWithoutEffects>;
```

Note that simplifying the frontmatter schema to a single field (e.g. `title: z.string()`) does not fix the issue.

---

Small question regarding the original issue: I'm not a huge TS project references user, but from my understanding, `declaration` is `true` as soon as `composite` is true but is there any reason why `composite` could not be set to `false` locally in the Starlight project? From the `composite` [documentation](https://www.typescriptlang.org/docs/handbook/project-references.html#composite), this is only needed for "referenced projects" which I would guess is not the case of a Starlight project which won't be build using `tsc --build` I guess?
Again, not a huge project references user so I may be totally wrong, and not asking in order to say "this should not be fixed" (this should be fixed) but more by curiosity about the setup of the project that requires this option to be set to `true` for Starlight.

**Comment by alexanderniebuhr** [comment]
> but is there any reason why composite could not be set to false locally in the Starlight project?

That is a really good question, the option is inherit from a shared `tsconfig.json` in the monorepository (https://github.com/astrolicious/dotdev/pull/1/files#diff-6b1fdfc59614e520241c7ff9ecdee17d0ad5da51a8568be338aaa85b2ca6d463), I don't know if you can override that & what that would mean for the monorepository?

But since that starlight project is only part of a Astro project, I guess disabling it, would break cross-package type-checking inside the monorepository if they are imported & used inside the Astro/Starlight project? Anyways, I haven't tested it, but I can't set it to `false` in the monorepository, so the only place would be the specific `tsconfig.json` for the Astro project...
