### ISSUE TITLE
Setting Astro `build.format` config breaks sidebar links

### ISSUE THREAD

**Issue by jamescmartinez** [withastro/starlight#180]
### What version of `starlight` are you using?

0.1.2

### What version of `astro` are you using?

2.6.1

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

**Expected**: sidebar links should not have a trailing slash when setting [Astro's build.format config](https://docs.astro.build/en/reference/configuration-reference/#buildformat) to `file`

**Actual**: they have a trailing slash, which causes the links to 404 in production builds

**How to reproduce**:

1. Clone the `build-format-file` branch of [this repo](https://github.com/mergentlabs/docs)
2. Comment out [line 8 of the Astro config](https://github.com/mergentlabs/docs/blob/main/astro.config.mjs#L8) that sets the base path to `/docs` (sorry, it's a temporary workaround for GitHub pages)
3. `npm run dev` to see the trailing `/` OR `npm run build && npm run preview` to get the 404s
4. Click any link in the sidebar
5. Smile at everyone's favorite sad piece of paper :)
<img width="135" alt="Screenshot 2023-06-08 at 5 40 36 PM" src="https://github.com/withastro/starlight/assets/1286597/97bfc892-e583-45a0-84be-f788a162f198">

### Link to Minimal Reproducible Example

https://github.com/mergentlabs/docs/tree/build-format-file

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the report @jamescmartinez! I can confirm we’re not currently respecting `build.format` or [`trailingSlash`](https://docs.astro.build/en/reference/configuration-reference/#trailingslash) when building links. Should be do-able though and would welcome a PR!

Our general method for making user configuration from `astro.config` available to components etc. is via virtual modules and you can see that in place here:

https://github.com/withastro/starlight/blob/7f4e948ee20a48d79ce6297e2aa7be923164ff6d/packages/starlight/index.ts#L85-L94

We currently expose the project `root` via the `virtual:starlight/project-context` virtual module, but could add `trailingSlash` and `build.format` to that module so that Starlight code can do something like:
```js
import project from 'virtual:starlight/project-context';

const link = project.build.format === 'file' ? '/foo.html' : '/foo/';
```

**Comment by jamescmartinez** [comment]
I didn't have time to wrap this up tonight, but here's a start: https://github.com/withastro/starlight/pull/207

**Comment by kevinzunigacuellar** [comment]
I would like to take a swing at this one 🚀
