### ISSUE TITLE
Inconsistent Behavior of Links in Starlight | Frontmatter Prev and Next

### ISSUE THREAD

**Issue by Neonsy** [withastro/starlight#1886]
### What version of `starlight` are you using?

0.22.4

### What version of `astro` are you using?

4.8.6

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Description

I've been experimenting with Starlight for a couple of days and have recently set up a project hosted on GitHub Pages. I've noticed that the behavior of the `Prev` and `Next` links is inconsistent and I'm unsure why this is happening.

### Details

The issue is that sometimes the links work as expected, and other times they don't. It seems that sometimes they need to be prefixed with the Astro config's `base` value, and other times they automatically prefix themselves.

To understand why the behavior changes, I created a fresh template install. In this template, I have three files in an auto-generated directory. Each file uses the exact same link. The link in `three.md` works, but the links in `one.md` and `two.md` do not.

In my actual documentation, I've tried prefixing the frontmatter links with the base value. Everything works with this prefixing, except for one file. I've also noticed odd differences where a link works in one test run and not in another. It seems whether the link is treated as relative or absolute, and whether it needs the base as a prefix, changes unpredictably.

### Steps to Reproduce

1. Create a fresh Starlight template.
2. Create a directory at `/src/content/docs/myfiles` within the new project.
3. Add three files (`one.md`, `two.md`, `three.md`) and add them to the sidebar config as auto-generated directory.
4. Use the same link in each file.

```js
---
title: one
sidebar:
    order: 1
next:
    label: example ref
    link: reference/example/
---

---
title: two
sidebar:
    order: 2
next:
    label: example ref
    link: reference/example/
---

---
title: three
sidebar:
    order: 3
next:
    label: example ref
    link: reference/example/
---
```

6. Observe that the link in `three.md` works, but the links in `one.md` and `two.md` do not.

### Expected Behavior

The links should consistently work across all files and should either all require manual prefixing with the base value or non of the links require the prefixing.

### Actual Behavior

The links work inconsistently. Sometimes they require manual prefixing with the base value, and other times they do not.

I believe this is not the intended behavior, hence I'm opening this issue. Any help or guidance would be greatly appreciated.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rzkjm9?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by DrNeonsy** [comment]
Thank you @delucis  for taking the time to review my issue. I appreciate your assistance in this matter.

To provide more context, I'd like to share a specific instance from my actual documentation where I've encountered this inconsistent behavior. Despite managing to resolve most of the link-related issues, there's one page that continues with the problematic behavior.

You can find this page at the following location: [Python Note Collection - Numbers](https://github.com/DrNeonsy/Python-Note-Collection/blob/neondocs/src/content/docs/Python/Operators/numbers.mdx).

This page, in particular, seems to be behaving differently from the rest, and I'm unsure why. Any insights or guidance you could provide would be greatly appreciated. Thank you again for your time and assistance.

**Comment by HiDeoo** [comment]
Had a bit of free time so I started investigating it. I did not have time yet to start a PR but wanted to share my findings.

If we take your last example and remove the `prev` and `next` frontmatter configuration, the page will automatically generate with a `prev` link and no `next` link. This is because the page is the last page of an autogenerated links group (so it has a previous page, but no next page).

When the `prev` and `next` frontmatter configuration are set, 2 different code paths are taken:

- `prev` link:
  - An automatically generated `prev` link already exists.
  - [Edit this link and use `prev.label` and `prev.link` from the frontmatter as is](https://github.com/withastro/starlight/blob/main/packages/starlight/utils/navigation.ts#L346-L350).
  - The valid `/Python-Note-Collection/python/basics/output` link will work.
- `next` link:
  - An automatically generated `next` link does not exist.
  - [Create a new link](https://github.com/withastro/starlight/blob/main/packages/starlight/utils/navigation.ts#L355-L357) with the `next.label` and `next.link` from the frontmatter.
  - The `makeLink()` function will [call](https://github.com/withastro/starlight/blob/main/packages/starlight/utils/navigation.ts#L141C10-L141C20) a `formatPath()` function using a path formatter that [automatically adds the `base` to the path](https://github.com/withastro/starlight/blob/main/packages/starlight/utils/createPathFormatter.ts#L42).
  - The valid `/Python-Note-Collection/python/basics/output` link will become `/Python-Note-Collection/Python-Note-Collection/python/basics/output` (and skipping the `base` using `/python/basics/datatypes` will become `/Python-Note-Collection/python/basics/datatypes` and be valid).

In this specific case, we want to use the provided `next.link` as is so I would guess there are multiple ways to fix this (and did not have time to think about the best way yet):

- Do we really need to call always call `formatPath()` in this specific case?
- Should the `base` be skipped in `formatPath()` when the path starts with it?
- Should the `base` be skipped in `formatPath()` based on a configuration/flag?
