### ISSUE TITLE
LastUpdated is Using the same date for all files 

### ISSUE THREAD

**Issue by sanabel-al-firdaws** [withastro/starlight#2084]
### What version of `starlight` are you using?

^0.24.4

### What version of `astro` are you using?

^4.11.0

### What package manager are you using?

bun (github pages)

### What operating system are you using?

linux

### What browser are you using?

edge and kiwi browser 

### Describe the Bug

when turning on LastUpdated in Astro config all files in the site has the same date

for example when i change a file today it becomes lastUpdated : 2024/7/4

but a file i didn't touch from 3 days ago becomes also lastUpdated 2024/7/4

this issue happened to me a long time ago and i forgot about it and now when i turned the thing on again the same issue

also here is a link to a file i didn't touch in 3 days it says its lastUpdated : today click edit this page link to see the date

### Link to Minimal Reproducible Example

https://sanabel-al-firdaws.github.io/theme

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @sanabel-al-firdaws!

I think the issue here is in the GitHub Action where you build the site.

If I build your repo locally, the correct date is shown, but I believe when the repo is checked out in GitHub Actions, currently it is a “shallow” clone without full history for the files.

To fix this you can add [`fetch-depth: 0`](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches) as an option in the checkout step of your [GitHub workflow file](https://github.com/sanabel-al-firdaws/sanabel-al-firdaws.github.io/blob/main/.github/workflows/deploy.yml):

```yml
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
```

**Comment by sanabel-al-firdaws** [comment]
thank you ✨✨❤️ I always wanted to use this feature but it didn't seem to work before

thank you for the great work on starlight !
