### ISSUE TITLE
MDX file importing Vue component, unable to parse Vue component

### ISSUE THREAD

**Issue by hanjiezhou** [withastro/starlight#2097]
### What version of `starlight` are you using?

0.24.3

### What version of `astro` are you using?

4.10.3

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

chrome

### Describe the Bug

MDX file importing Vue component, unable to parse Vue component
![image](https://github.com/withastro/starlight/assets/101302973/362e2fa2-4113-4cf7-a50e-464a031f5271)
![image](https://github.com/withastro/starlight/assets/101302973/4a139479-216b-46b8-96b9-5d1d3f4eb39c)
![image](https://github.com/withastro/starlight/assets/101302973/53c88f02-10cc-4643-979c-b6770a9b22cb)
May I ask how to solve this problem？

### Link to Minimal Reproducible Example

nothing

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @hanjiezhou! It looks like this isn’t an issue with Starlight, but with how you have configured those custom elements: `<el-card>`, `<el-alert>` etc.

The warnings in the console say Vue is trying to resolve those somehow. Not sure if that’s intentional or if you need to follow those instructions to exclude those tag names?
