### ISSUE TITLE
In i18n folder names cannot contain uppercase letters.

### ISSUE THREAD

**Issue by ax-6** [withastro/starlight#2244]
### What version of `starlight` are you using?

latest

### What version of `astro` are you using?

latest

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Edge

### Describe the Bug

In i18n folder names cannot contain uppercase letters.
Details: [https://github.com/aq-org/Docs/issues/18](https://github.com/aq-org/Docs/issues/18)

### Link to Minimal Reproducible Example

https://deploy-preview-17--aq-docs.netlify.app/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ax-6** [comment]
You will find that the language selection in this link has no effect, because the browser seems to automatically change the directory to lower case.

**Comment by ax-6** [comment]
But I don't think it's a browser problem, it should be a small error in Starlight's build system, which causes the language folder containing uppercase letters to not be output properly.

**Comment by ax-6** [comment]
This is not a big problem, if it cannot be fixed, you can post a NOTE in the docs to remind people not to use the i18n folder with uppercase.

**Comment by lorenzolewis** [comment]
This isn't so much an Astro or Starlight specific problem, but is caused by [different filesystems treating case-sensitivity differently](https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity#differences-between-windows-and-linux-case-sensitivity). For example, NTFS ignores case sensitivity, APFS (on macOS and iOS systems) has two different options for sensitivity, and Linux I'm sure has a whole other set that I'm not familiar with. 

However, as you've discovered, [a URL _is_ indeed case-sensitive](https://www.w3.org/TR/WD-html40-970708/htmlweb.html). 

Additionally, each platform you use to deploy your site may have different options/behavior for how they handle this when serving a site. It looks like you're using Netlify (at least for your PR previews) and it looks like their behavior is to normalize any URLs to be lowercase: https://answers.netlify.com/t/how-to-disable-uppercase-urls-are-redirected-to-lowercase-urls-feature/89469

With that in mind, I would personally recommend using all lowercase letters for your filenames and go with the lowest common denominator with the expectation that some filesystems just tend to ignore case completely. 

I understand this may not solve your specific issue, but I hope this helps to explain this behavior and give some solutions and workarounds to prevent it from happening for you.
