### ISSUE TITLE
Code blocks that are too long will overflow the page

### ISSUE THREAD

**Issue by pixelpilotUm** [withastro/starlight#2305]
### Astro Info

```block
I don't think it's necessary to run this command
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

![image](https://github.com/user-attachments/assets/7caee1da-b793-4b00-a380-7b107dbded54)
Code blocks that are too long will overflow the page

### What's the expected result?

I hope the new version can solve this problem

### Link to Minimal Reproducible Example

https://docs.pixelpilot.top/nextjs/ssr-strategy/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your feedback.

I'm assuming <https://github.com/pixelpilotUm/my-web-Learning-Docs> is the repo you're referring to. If yes, it looks like this page is written in Markdoc (`src/content/docs/Next.js/SSR-Strategy.mdoc`).

We just released a few days ago a Starlight Markdoc preset that automatically configure Markdoc so that Starlight components are used automatically. Following the ["Add Markdoc to an existing project" guide](https://starlight.astro.build/guides/authoring-content/#add-markdoc-to-an-existing-project) should fix this issue.

For example, after following this guide locally and not doing any change to the content, the page looks like this:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/3ce1ec40-b274-4024-8087-0c9d496d12da">

Note that the lack of syntax highlighting is due to the fact that the code block is missing a language identifier but adding `tsx` fixes it.

**Comment by pixelpilotUm** [comment]
> Thanks for your feedback. 
> 
> I'm assuming https://github.com/pixelpilotUm/my-web-Learning-Docs is the repo you're referring to. If yes, it looks like this page is written in Markdoc (`src/content/docs/Next.js/SSR-Strategy.mdoc`). 
> 
> We just released a few days ago a Starlight Markdoc preset that configure Markdoc so that Starlight components are used automatically. Following the ["Add Markdoc to an existing project" guide](https://starlight.astro.build/guides/authoring-content/#add-markdoc-to-an-existing-project) and starting at the step number 2 (as you already have the Astro’s Markdoc integration installed) should fix this issue. 
> 
> For example, after following this guide locally and not doing any change to the content, the page looks like this: 
> 
> <img alt="image" width="762" src="https://private-user-images.githubusercontent.com/494699/365456961-3ce1ec40-b274-4024-8087-0c9d496d12da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTYwMjAsIm5iZiI6MTcyNTg1NTcyMCwicGF0aCI6Ii80OTQ2OTkvMzY1NDU2OTYxLTNjZTFlYzQwLWIyNzQtNDAyNC04MDg3LTBjOWQ0OTZkMTJkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwNDIyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzkzNjYxODU3NDM4YzI1YTAyZTgxYWE2OWY2MzMyNzhkMmFhNGNiMjE5ZmZlMTkzZWRlNDRhNTllYjFmNTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.70hxGqRKMxrBU9bskxKf2PAGlmXOI9SNFaMJg_siL0Q">
> Note that the lack of syntax highlighting is due to the fact that the code block is missing a language identifier but adding `tsx` fixes it.

Thank you, your answer has basically solved my problem. I apologize, I shouldn't have posted the question in `astro`, it should have been posted in the theme repository. At the same time, I would like to thank you again for your answer and for solving my problem.
