### ISSUE TITLE
Enable support for non-svg format favicons

### ISSUE THREAD

**Issue by squpshift** [withastro/starlight#363]
### What version of `starlight` are you using?

0.5.4

### What is your idea?

Add favicon file path as a configuration setting

### Why is this feature necessary?

svg is not supported by all browsers. Visiting a starlight docs site in Safari for example does not load any favicon.

https://caniuse.com/link-icon-svg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue! We were just discussing this yesterday. Totally agree — in fact I had missed that Safari doesn’t support SVG favicons yet.

Just read up on some recommendations in this [“How to favicon” article](https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs).

I think we can skip its larger icon recommendations (those are used when adding sites to home screens on iOS/Android and are still possible for anyone who really needs them by dropping those additional files in `public/` and using Starlight’s `head` config option).

So that leaves their recommendation as:
```html
<link rel="icon" href="/favicon.ico" sizes="32x32">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
```

In other words: an SVG icon for _most_ modern browsers, a `.ico` file for everyone else.

Needing two makes this not super friendly to design config for. I wonder if the simplest is to add a `favicon` config option that configures our existing `/favicon.svg` path, and leave adding a `.ico` fallback to users who really want it (Starlight sites don’t support IE, so seems to be only Safari that would need it).

In other words:

- Default behaviour remains the same as currently — we expect a `favicon.svg` and link to it in `<head>` (doesn’t work in Safari)
- Users can either:
  - Set a `favicon` option to a new path if they prefer to use a different format/filename:
     ```js
     starlight({
       favicon: '/favicon.png',
     })
     ```
  - Or stick to SVG for their primary icon, and add a `.ico` fallback via Starlight’s `head` config:
     ```js
     starlight({
       head: [
         {
           tag: 'link',
           attrs: { rel: 'icon', href:'/favicon.ico', sizes: '32x32' },
         }
       ],
     })
     ```

**Comment by HiDeoo** [comment]
> * Default behaviour remains the same as currently — we expect a `favicon.svg` and link to it in `<head>` (doesn’t work in Safari)

This sounded a bit weird to me at first to not have a Safari favicon by default but after a bit of research, this may indeed be the better solution as the `sizes` attributes trick mentioned in the article seems to [not work](https://twitter.com/subzey/status/1636955352670281730) like it was before. It looks like now Chrome will still use the SVG but it will also download the ICO file which is usually larger even if not used.

API-wise, I wonder if we really need a `favicon` property, couldn't we conditionally include the default `favicon.svg` only if the user config does not contains a `head` entry for a `link` tag with a `rel` of `icon`? My reasonning is that if a user does not have an SVG but wants to have a PNG and a ICO file, they would have make changes at two places in the configuration instead of just configuring both links in the `head` property only. Any thoughts?

**Comment by delucis** [comment]
> if you configure any icon, you configure them all.

That’s an option. My main motivation was to make this simple: the `head` syntax is significantly more verbose and kind of gross because you’re writing full HTML tags but in this weird object syntax (I’m allowed to say it because I made it 😅) — it’s probably easy for people to mess up.

<details>
<summary>(Aside about why head is configurable like this even if it’s gross)</summary>

The reason `head` _does_ support this odd syntax instead of just having people provide a component or something is precisely to do some deduplication as suggested: if you set `<title>` via `head` we ensure there’s only one, and the same for some `<meta>` tags ([source code](https://github.com/withastro/starlight/blob/3311435b10517a225c78bc23e5ad3ffcc0f659d9/packages/starlight/utils/head.ts#L65-L67)). This is a bit trickier for `<link>` tags where there aren’t really any rules that say you shouldn’t duplicate things. We could of course special case the default favicon tag as suggested though.

</details>

To demonstrate, here’s the current favicon logic which is actually also in this format:
https://github.com/withastro/starlight/blob/3311435b10517a225c78bc23e5ad3ffcc0f659d9/packages/starlight/components/HeadSEO.astro#L37-L44

Folks need to remember to add their `base` potentially (we don’t process head tags at all), plus should add a MIME type ideally. That’s stuff we could handle pretty easily for them and hide a bit of complexity.

---

To play devil’s advocate: if the recommendation is to always use SVG and then add a `.ico` as a fallback, maybe the answer is we _require_ `.svg` like today, and if needed users can add a `.ico` fallback via `head` as shown in my [previous comment](https://github.com/withastro/starlight/issues/363#issuecomment-1643725428). Seems a bit hardline, but maybe OK?

**Comment by HiDeoo** [comment]
> Folks need to remember to add their base potentially (we don’t process head tags at all), plus should add a MIME type ideally.

Yeah, that's a strong point. I may have suggested something a bit too rough and the fact that we still need articles like the excellent one you linked is proof that it is super easy to mess up or forget something.

I would assume requiring an SVG may also be a bit too much as I guess some people may only have a PNG logo with no vector based version.

Taking all this into consideration again, I think I will personally side back on your initial proposal 👍

**Comment by delucis** [comment]
Ok cool, sounds like we have a plan to add a favicon option, which would have a schema of `z.string().default('/favicon.svg')` and preserve the current default behaviour.

Unlike the logo in the site header, I don't think this should be a path we import and hash via Vite a) because that makes default behaviour trickier and b) because a static URL to a favicon seems to be recommended for third-party services that might fetch it. So just a string and we can do some simple extension based guessing to decide MIME type.

**Comment by delucis** [comment]
That sounds awesome — thanks for picking this up @HiDeoo! Will get #383 merged now 🙌
