### ISSUE TITLE
Dynamically adding a new Page/Route

### ISSUE THREAD

**Issue by mirrorleap** [withastro/starlight#379]
### What version of `starlight` are you using?

0.5.5

### What is your idea?

Introduce the possibility to dynamically add a new page/route to Starlight docs, without re-building the whole site.

### Why is this feature necessary?

The way Starlight works is that your author your content in Markdown (`.md` or `.mdx`) and it transforms them into static html pages when the site is built with `astro build`. This means every time you author a new page, a build step is necessary to generate page's html and update navigation.

It will be quite useful, if a user could add a page dynamically to an already built site. Currently the only way I found to do this, is to manually create a new folder and add `index.html` file to the `dist` folder. For example -

Already built page:
- dist/guides/guide1/index.html

Manually added new page:
- dist/guides/guide2/index.html

However, this is not ideal. Firstly, we need to manually create the html page rather than just authoring content in markdown. Secondary, it won't update the site's navigation unless done manually.

This feature will be especially useful, if a user wants to connect a Backend or CMS to the docs site. Perhaps, SSR support is needed for Starlight to implement this feature. Or maybe there could be some other approach.

### Do you have examples of this feature in other projects?

Docsify (documentation builder) supports this feature, however it does this by dynamically parsing the markdown content and live reloading the site on change.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @mirrorleap! Thanks for the issue.

Starlight builds on top of Astro and this kind of feature would need to be implemented there. There have been a few discussions about this:
- https://github.com/withastro/roadmap/discussions/237
- https://github.com/withastro/roadmap/discussions/228
And a community member has been working on an experimental guide here: https://github.com/withastro/docs/pull/3527

Because this wouldn’t be at the Starlight level I’ll close this here and you can follow some of those links to track progress.
