### ISSUE TITLE
Mandatory checkbox in Bug Report template

### ISSUE THREAD

**Issue by maheshrijal** [withastro/starlight#732]
### What version of `starlight` are you using?

NA

### What version of `astro` are you using?

NA

### What package manager are you using?

NA

### What operating system are you using?

NA

### What browser are you using?

NA

### Describe the Bug

I was experimenting with mandatory check boxes for bug report template when I noticed the bug report template for starlight has "text" check-boxes. 

![image](https://github.com/withastro/starlight/assets/62394512/6e63f3c7-03ae-4e4b-8ec6-770eef6fd066)

If these checks are mandatory, better would be to add an actual checkbox. 

This can be done with a quick edit to the bug template. 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the idea! I think I prefer hearing from folks rather than throwing up this specific barrier. The text version is to help people remember to check these, but I don’t think we need to block if they forget. Adding a checkbox would also result in the checkbox text showing up in the issue body, which seems unnecessarily noisy.
