### ISSUE TITLE
`base` url configuration is not applied to internal links within markdown

### ISSUE THREAD

**Issue by skaaks** [withastro/starlight#932]
### What version of `starlight` are you using?

0.11.1

### What version of `astro` are you using?

3.2.3

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I am trying to create a static documentation using astro starlight. As part of the requirement, the website is supposed to be deployed to a subpath on the main domain e.g. `https://<mydomain>/subPath`. After looking at the astro documentation, I set [`base`](https://docs.astro.build/en/reference/configuration-reference/#base) configuration to `/subPath` to achieve this.

To my surprise, this didn't work as expected. Many links were broken in the final build:

* In a page with `splash` template, all the links provided within `hero.actions` frontmatter were not updated with the base url.
* Any internal links used within the markdown files for linking different pages with each other were not updated with the base url.

However, all links which are part of sidebar were properly updated with base url. Same is true for prev/next links in the footer and the links provided as part of the search results.

I have tried to create a reproducible [example](https://stackblitz.com/edit/github-mxm5oj). It is built on top of the basic example provided with starlight. I have updated following:

* added `base: '/subPath'` config in `astro.config.mjs`.
* added an internal link to the reference page in `guides/example.md`.

What am I missing and how can I achieve the desired behavior?

PS: Do note that when running the example stackbitz might complain about the subpath. You will need to add `/subPath` at the end of the url to access the final website.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mxm5oj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kevinmichaelchen** [comment]
* [For the links in the Hero's CTAs](https://github.com/withastro/starlight/blob/01190b3be64981f2d375594094f685ff6e9238c0/packages/starlight/components/CallToAction.astro#L14-L18)
  * seems straightforward to modify?
  * [we just add `BASE_URL` — similar to here](https://github.com/withastro/starlight/blob/01190b3be64981f2d375594094f685ff6e9238c0/packages/starlight/utils/localizedUrl.ts#L14-L16)
* Markdown links seem trickier 
  * Very relevant [Astro GH Issue](https://github.com/withastro/astro/issues/5680)
    * [rehype plugin to transform relative links in md/mdx](https://github.com/vernak2539/astro-rehype-relative-markdown-links)
    * [related RFC about astro+markdown](https://github.com/withastro/roadmap/discussions/424)

**Comment by delucis** [comment]
Thanks for the issue @skaaks!

This behaviour is intentional. When a Markdown link is relative, e.g. to `/some-page`, we can’t know for sure that you want that link to be relative to your configured `base`. For example, you may have a site at `example.com` and docs on a subpath at `example.com/docs`. You might link from docs to your main site’s homepage with `/` or to a page on your main site with `/page`. If we prepended `base` automatically, this would prevent you linking up and out of your subpath site with a relative link.

The same reasoning applies to the CTAs in the hero component.

That said, if you know this is not the case for your specific project, then using a plugin like the one shared by @kevinmichaelchen is a good solution for Markdown links.

**Comment by kevinmichaelchen** [comment]
> You might link from docs to your main site’s homepage with `/`

This clicked for me.
